import type { Profile, Milestone, Education } from "./store";

export type TimelineItem = {
  id: string;
  title: string;
  milestoneDate: string;
  category: "achievement" | "promotion" | "certification" | "education" | "milestone" | "celebration" | "other";
  icon: string;
  isAutoGenerated: boolean;
  createdBy?: string;
};

export type HomeData = {
  profile: Profile;
  tenureYears: number | null;
  tenureProgressPercent: number;
  skillsCount: number;
  promotions: number;
  certifications: number;
  totalMilestones: number;
  leftColumn: TimelineItem[];
  rightColumn: TimelineItem[];
  rightEmptyReason: "no-education" | "no-joining-date" | null;
};

const CERT_KEYWORDS = [
  "certified", "certification", "certificate", "cka", "ckad",
  "aws", "gcp", "azure", "pmp", "istqb", "comptia", "cisco",
  "terraform", "hashicorp", "google", "hubspot", "databricks",
  "redis", "mongodb", "professional credential",
];

function isCertification(title: string): boolean {
  const lower = title.toLowerCase();
  return CERT_KEYWORDS.some((kw) => lower.includes(kw));
}

function fullYearsBetween(from: Date, to: Date): number {
  let years = to.getFullYear() - from.getFullYear();
  const monthDiff = to.getMonth() - from.getMonth();
  if (monthDiff < 0 || (monthDiff === 0 && to.getDate() < from.getDate())) {
    years--;
  }
  return Math.max(0, years);
}

function progressToNextAnniversary(joiningDate: Date, today: Date): number {
  const years = fullYearsBetween(joiningDate, today);
  const lastAnniversary = new Date(joiningDate);
  lastAnniversary.setFullYear(joiningDate.getFullYear() + years);
  const nextAnniversary = new Date(joiningDate);
  nextAnniversary.setFullYear(joiningDate.getFullYear() + years + 1);
  const total = nextAnniversary.getTime() - lastAnniversary.getTime();
  const elapsed = today.getTime() - lastAnniversary.getTime();
  return Math.min(100, Math.max(0, Math.round((elapsed / total) * 100)));
}

function generateAutoEntries(profile: Profile): TimelineItem[] {
  const entries: TimelineItem[] = [];
  const today = new Date();

  if (profile.joiningDate) {
    const jd = new Date(`${profile.joiningDate}T00:00:00`);

    entries.push({
      id: "auto-joined",
      title: "Joined the Team",
      milestoneDate: profile.joiningDate,
      category: "milestone",
      icon: "👋",
      isAutoGenerated: true,
    });

    const years = fullYearsBetween(jd, today);
    for (let y = 1; y <= years; y++) {
      const d = new Date(jd);
      d.setFullYear(jd.getFullYear() + y);
      entries.push({
        id: `auto-anniversary-${y}`,
        title: `${y} Year Work Anniversary`,
        milestoneDate: d.toISOString().slice(0, 10),
        category: "milestone",
        icon: "🎂",
        isAutoGenerated: true,
      });
    }
  }

  if (profile.dateOfBirth) {
    const dob = new Date(`${profile.dateOfBirth}T00:00:00`);
    const bday = new Date(dob);
    bday.setFullYear(today.getFullYear());
    if (bday > today) bday.setFullYear(today.getFullYear() - 1);
    entries.push({
      id: "auto-birthday",
      title: "Birthday",
      milestoneDate: bday.toISOString().slice(0, 10),
      category: "celebration",
      icon: "🎉",
      isAutoGenerated: true,
    });
  }

  return entries;
}

function educationToTimelineItems(education: Education[], joiningDate: string | null): TimelineItem[] {
  return education
    .filter((e) => {
      if (!joiningDate) return true;
      const joiningYear = new Date(`${joiningDate}T00:00:00`).getFullYear();
      return e.year >= joiningYear;
    })
    .map((e, i) => {
      const cat = isCertification(e.degree) ? "certification" as const : "education" as const;
      return {
        id: `edu-${i}`,
        title: e.degree,
        milestoneDate: `${e.year}-${String(e.month ?? 6).padStart(2, "0")}-01`,
        category: cat,
        icon: cat === "certification" ? "⭐" : "📚",
        isAutoGenerated: true,
      };
    });
}

export function buildHomeData(profile: Profile, milestones: Milestone[]): HomeData {
  const today = new Date();
  let tenureYears: number | null = null;
  let tenureProgressPercent = 0;

  if (profile.joiningDate) {
    const jd = new Date(`${profile.joiningDate}T00:00:00`);
    tenureYears = fullYearsBetween(jd, today);
    tenureProgressPercent = progressToNextAnniversary(jd, today);
  }

  const promotions = milestones.filter((m) => m.category === "promotion").length;

  // Left column: all milestones (any category) + auto-generated entries
  const storedItems: TimelineItem[] = milestones.map((m) => ({
    id: m.id,
    title: m.title,
    milestoneDate: m.milestoneDate,
    category: m.category,
    icon: ({ achievement: "🏆", promotion: "📈", milestone: "🏅", celebration: "🎉", other: "📌", certification: "⭐", education: "📚" })[m.category] ?? "📌",
    isAutoGenerated: false,
    createdBy: m.createdBy,
  }));

  const autoItems = generateAutoEntries(profile);
  const leftColumn = [...storedItems, ...autoItems].sort(
    (a, b) => (a.milestoneDate < b.milestoneDate ? 1 : -1),
  );

  // Right column: from profiles.education filtered by joining_date
  const eduItems = educationToTimelineItems(profile.education, profile.joiningDate);
  const rightColumn = eduItems.sort(
    (a, b) => (a.milestoneDate < b.milestoneDate ? 1 : -1),
  );

  const certifications = rightColumn.filter((i) => i.category === "certification").length;

  let rightEmptyReason: HomeData["rightEmptyReason"] = null;
  if (rightColumn.length === 0) {
    rightEmptyReason = profile.education.length === 0 ? "no-education" : "no-joining-date";
  }

  return {
    profile,
    tenureYears,
    tenureProgressPercent,
    skillsCount: profile.skills.length,
    promotions,
    certifications,
    totalMilestones: milestones.length,
    leftColumn,
    rightColumn,
    rightEmptyReason,
  };
}
