import type { Profile, Milestone, MilestoneCategory } from "./store";

export type TimelineItem = {
  id: string;
  title: string;
  milestoneDate: string;
  category: MilestoneCategory;
  icon: string;
  isAutoGenerated: boolean;
  createdBy?: string;
};

export type HomeData = {
  profile: Profile;
  tenureYears: number | null;
  tenureProgressPercent: number;
  skillsCount: number;
  promotions: number;
  certifications: number;
  totalMilestones: number;
  leftColumn: TimelineItem[];
  rightColumn: TimelineItem[];
};

const CATEGORY_ICON: Record<string, string> = {
  achievement: "🏆",
  promotion: "📈",
  certification: "⭐",
  education: "📚",
  other: "📌",
  milestone: "🏅",
};

const LEFT_CATEGORIES = new Set(["achievement", "promotion", "milestone", "other"]);

function fullYearsBetween(from: Date, to: Date): number {
  let years = to.getFullYear() - from.getFullYear();
  const monthDiff = to.getMonth() - from.getMonth();
  if (monthDiff < 0 || (monthDiff === 0 && to.getDate() < from.getDate())) {
    years--;
  }
  return Math.max(0, years);
}

function progressToNextAnniversary(joiningDate: Date, today: Date): number {
  const years = fullYearsBetween(joiningDate, today);
  const lastAnniversary = new Date(joiningDate);
  lastAnniversary.setFullYear(joiningDate.getFullYear() + years);
  const nextAnniversary = new Date(joiningDate);
  nextAnniversary.setFullYear(joiningDate.getFullYear() + years + 1);
  const total = nextAnniversary.getTime() - lastAnniversary.getTime();
  const elapsed = today.getTime() - lastAnniversary.getTime();
  return Math.min(100, Math.max(0, Math.round((elapsed / total) * 100)));
}

function generateAutoEntries(profile: Profile): TimelineItem[] {
  const entries: TimelineItem[] = [];
  const today = new Date();

  if (profile.joiningDate) {
    const jd = new Date(`${profile.joiningDate}T00:00:00`);

    entries.push({
      id: "auto-joined",
      title: "Joined the Team",
      milestoneDate: profile.joiningDate,
      category: "milestone",
      icon: "👋",
      isAutoGenerated: true,
    });

    const years = fullYearsBetween(jd, today);
    for (let y = 1; y <= years; y++) {
      const d = new Date(jd);
      d.setFullYear(jd.getFullYear() + y);
      entries.push({
        id: `auto-anniversary-${y}`,
        title: `${y} Year Work Anniversary`,
        milestoneDate: d.toISOString().slice(0, 10),
        category: "milestone",
        icon: "🎂",
        isAutoGenerated: true,
      });
    }
  }

  if (profile.dateOfBirth) {
    const dob = new Date(`${profile.dateOfBirth}T00:00:00`);
    const bday = new Date(dob);
    bday.setFullYear(today.getFullYear());
    if (bday > today) bday.setFullYear(today.getFullYear() - 1);
    entries.push({
      id: "auto-birthday",
      title: "Birthday",
      milestoneDate: bday.toISOString().slice(0, 10),
      category: "milestone",
      icon: "🎉",
      isAutoGenerated: true,
    });
  }

  return entries;
}

export function buildHomeData(profile: Profile, milestones: Milestone[]): HomeData {
  const today = new Date();
  let tenureYears: number | null = null;
  let tenureProgressPercent = 0;

  if (profile.joiningDate) {
    const jd = new Date(`${profile.joiningDate}T00:00:00`);
    tenureYears = fullYearsBetween(jd, today);
    tenureProgressPercent = progressToNextAnniversary(jd, today);
  }

  const promotions = milestones.filter((m) => m.category === "promotion").length;
  const certifications = milestones.filter((m) => m.category === "certification").length;

  const storedItems: TimelineItem[] = milestones.map((m) => ({
    id: m.id,
    title: m.title,
    milestoneDate: m.milestoneDate,
    category: m.category,
    icon: CATEGORY_ICON[m.category] ?? "📌",
    isAutoGenerated: false,
    createdBy: m.createdBy,
  }));

  const autoItems = generateAutoEntries(profile);
  const allItems = [...storedItems, ...autoItems].sort(
    (a, b) => (a.milestoneDate < b.milestoneDate ? 1 : -1),
  );

  const leftColumn = allItems.filter((i) => LEFT_CATEGORIES.has(i.category));
  const rightColumn = allItems.filter((i) => !LEFT_CATEGORIES.has(i.category));

  return {
    profile,
    tenureYears,
    tenureProgressPercent,
    skillsCount: profile.skills.length,
    promotions,
    certifications,
    totalMilestones: milestones.length,
    leftColumn,
    rightColumn,
  };
}
